/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthSuccessRouteImport } from './routes/auth/success'
import { Route as AuthVerifyMfaRouteImport } from './routes/auth/verify-mfa'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardEmployeesRouteImport } from './routes/dashboard/employees'
import { Route as DashboardEmployeesIndexRouteImport } from './routes/dashboard/employees.index'
import { Route as DashboardEmployeesIdRouteImport } from './routes/dashboard/employees.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyMfaRoute = AuthVerifyMfaRouteImport.update({
  id: '/auth/verify-mfa',
  path: '/auth/verify-mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesRoute = DashboardEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesIndexRoute = DashboardEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEmployeesRoute,
} as any)
const DashboardEmployeesIdRoute = DashboardEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardEmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
  '/dashboard/employees': typeof DashboardEmployeesRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/employees/$id': typeof DashboardEmployeesIdRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/employees/$id': typeof DashboardEmployeesIdRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
  '/dashboard/employees': typeof DashboardEmployeesRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/employees/$id': typeof DashboardEmployeesIdRoute
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/auth/success'
    | '/auth/verify-mfa'
    | '/dashboard/employees'
    | '/dashboard/'
    | '/dashboard/employees/$id'
    | '/dashboard/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/auth/success'
    | '/auth/verify-mfa'
    | '/dashboard'
    | '/dashboard/employees/$id'
    | '/dashboard/employees'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/auth/success'
    | '/auth/verify-mfa'
    | '/dashboard/employees'
    | '/dashboard/'
    | '/dashboard/employees/$id'
    | '/dashboard/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  AuthVerifyMfaRoute: typeof AuthVerifyMfaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-mfa': {
      id: '/auth/verify-mfa'
      path: '/auth/verify-mfa'
      fullPath: '/auth/verify-mfa'
      preLoaderRoute: typeof AuthVerifyMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees': {
      id: '/dashboard/employees'
      path: '/employees'
      fullPath: '/dashboard/employees'
      preLoaderRoute: typeof DashboardEmployeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees/': {
      id: '/dashboard/employees/'
      path: '/'
      fullPath: '/dashboard/employees/'
      preLoaderRoute: typeof DashboardEmployeesIndexRouteImport
      parentRoute: typeof DashboardEmployeesRoute
    }
    '/dashboard/employees/$id': {
      id: '/dashboard/employees/$id'
      path: '/$id'
      fullPath: '/dashboard/employees/$id'
      preLoaderRoute: typeof DashboardEmployeesIdRouteImport
      parentRoute: typeof DashboardEmployeesRoute
    }
  }
}

interface DashboardEmployeesRouteChildren {
  DashboardEmployeesIdRoute: typeof DashboardEmployeesIdRoute
  DashboardEmployeesIndexRoute: typeof DashboardEmployeesIndexRoute
}

const DashboardEmployeesRouteChildren: DashboardEmployeesRouteChildren = {
  DashboardEmployeesIdRoute: DashboardEmployeesIdRoute,
  DashboardEmployeesIndexRoute: DashboardEmployeesIndexRoute,
}

const DashboardEmployeesRouteWithChildren =
  DashboardEmployeesRoute._addFileChildren(DashboardEmployeesRouteChildren)

interface DashboardRouteChildren {
  DashboardEmployeesRoute: typeof DashboardEmployeesRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEmployeesRoute: DashboardEmployeesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  AuthVerifyMfaRoute: AuthVerifyMfaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
