/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthSuccessRouteImport } from './routes/auth/success'
import { Route as AuthVerifyMfaRouteImport } from './routes/auth/verify-mfa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyMfaRoute = AuthVerifyMfaRouteImport.update({
  id: '/auth/verify-mfa',
  path: '/auth/verify-mfa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/auth/success' | '/auth/verify-mfa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/auth/success' | '/auth/verify-mfa'
  id: '__root__' | '/' | '/sign-in' | '/auth/success' | '/auth/verify-mfa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  AuthVerifyMfaRoute: typeof AuthVerifyMfaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-mfa': {
      id: '/auth/verify-mfa'
      path: '/auth/verify-mfa'
      fullPath: '/auth/verify-mfa'
      preLoaderRoute: typeof AuthVerifyMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  AuthVerifyMfaRoute: AuthVerifyMfaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
