/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthSuccessRouteImport } from './routes/auth/success'
import { Route as AuthVerifyMfaRouteImport } from './routes/auth/verify-mfa'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardContributionTablesRouteImport } from './routes/dashboard/contribution-tables'
import { Route as DashboardEmployeesRouteImport } from './routes/dashboard/employees'
import { Route as DashboardMyPayslipsRouteImport } from './routes/dashboard/my-payslips'
import { Route as DashboardPayRunsRouteImport } from './routes/dashboard/pay-runs'
import { Route as DashboardTaxTablesRouteImport } from './routes/dashboard/tax-tables'
import { Route as DashboardEmployeesIndexRouteImport } from './routes/dashboard/employees.index'
import { Route as DashboardEmployeesIdRouteImport } from './routes/dashboard/employees.$id'
import { Route as DashboardMyPayslipsIndexRouteImport } from './routes/dashboard/my-payslips.index'
import { Route as DashboardMyPayslipsPayslipIdRouteImport } from './routes/dashboard/my-payslips.$payslipId'
import { Route as DashboardPayRunsIndexRouteImport } from './routes/dashboard/pay-runs.index'
import { Route as DashboardPayRunsIdRouteImport } from './routes/dashboard/pay-runs.$id'
import { Route as DashboardPayRunsIdIndexRouteImport } from './routes/dashboard/pay-runs.$id.index'
import { Route as DashboardPayRunsIdPayslipsPayslipIdRouteImport } from './routes/dashboard/pay-runs.$id.payslips.$payslipId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyMfaRoute = AuthVerifyMfaRouteImport.update({
  id: '/auth/verify-mfa',
  path: '/auth/verify-mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContributionTablesRoute =
  DashboardContributionTablesRouteImport.update({
    id: '/contribution-tables',
    path: '/contribution-tables',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmployeesRoute = DashboardEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyPayslipsRoute = DashboardMyPayslipsRouteImport.update({
  id: '/my-payslips',
  path: '/my-payslips',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPayRunsRoute = DashboardPayRunsRouteImport.update({
  id: '/pay-runs',
  path: '/pay-runs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTaxTablesRoute = DashboardTaxTablesRouteImport.update({
  id: '/tax-tables',
  path: '/tax-tables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesIndexRoute = DashboardEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEmployeesRoute,
} as any)
const DashboardEmployeesIdRoute = DashboardEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardEmployeesRoute,
} as any)
const DashboardMyPayslipsIndexRoute =
  DashboardMyPayslipsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMyPayslipsRoute,
  } as any)
const DashboardMyPayslipsPayslipIdRoute =
  DashboardMyPayslipsPayslipIdRouteImport.update({
    id: '/$payslipId',
    path: '/$payslipId',
    getParentRoute: () => DashboardMyPayslipsRoute,
  } as any)
const DashboardPayRunsIndexRoute = DashboardPayRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPayRunsRoute,
} as any)
const DashboardPayRunsIdRoute = DashboardPayRunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardPayRunsRoute,
} as any)
const DashboardPayRunsIdIndexRoute = DashboardPayRunsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPayRunsIdRoute,
} as any)
const DashboardPayRunsIdPayslipsPayslipIdRoute =
  DashboardPayRunsIdPayslipsPayslipIdRouteImport.update({
    id: '/payslips/$payslipId',
    path: '/payslips/$payslipId',
    getParentRoute: () => DashboardPayRunsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
  '/dashboard/contribution-tables': typeof DashboardContributionTablesRoute
  '/dashboard/employees': typeof DashboardEmployeesRouteWithChildren
  '/dashboard/my-payslips': typeof DashboardMyPayslipsRouteWithChildren
  '/dashboard/pay-runs': typeof DashboardPayRunsRouteWithChildren
  '/dashboard/tax-tables': typeof DashboardTaxTablesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/employees/$id': typeof DashboardEmployeesIdRoute
  '/dashboard/my-payslips/$payslipId': typeof DashboardMyPayslipsPayslipIdRoute
  '/dashboard/pay-runs/$id': typeof DashboardPayRunsIdRouteWithChildren
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/my-payslips/': typeof DashboardMyPayslipsIndexRoute
  '/dashboard/pay-runs/': typeof DashboardPayRunsIndexRoute
  '/dashboard/pay-runs/$id/': typeof DashboardPayRunsIdIndexRoute
  '/dashboard/pay-runs/$id/payslips/$payslipId': typeof DashboardPayRunsIdPayslipsPayslipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
  '/dashboard/contribution-tables': typeof DashboardContributionTablesRoute
  '/dashboard/tax-tables': typeof DashboardTaxTablesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/employees/$id': typeof DashboardEmployeesIdRoute
  '/dashboard/my-payslips/$payslipId': typeof DashboardMyPayslipsPayslipIdRoute
  '/dashboard/employees': typeof DashboardEmployeesIndexRoute
  '/dashboard/my-payslips': typeof DashboardMyPayslipsIndexRoute
  '/dashboard/pay-runs': typeof DashboardPayRunsIndexRoute
  '/dashboard/pay-runs/$id': typeof DashboardPayRunsIdIndexRoute
  '/dashboard/pay-runs/$id/payslips/$payslipId': typeof DashboardPayRunsIdPayslipsPayslipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
  '/dashboard/contribution-tables': typeof DashboardContributionTablesRoute
  '/dashboard/employees': typeof DashboardEmployeesRouteWithChildren
  '/dashboard/my-payslips': typeof DashboardMyPayslipsRouteWithChildren
  '/dashboard/pay-runs': typeof DashboardPayRunsRouteWithChildren
  '/dashboard/tax-tables': typeof DashboardTaxTablesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/employees/$id': typeof DashboardEmployeesIdRoute
  '/dashboard/my-payslips/$payslipId': typeof DashboardMyPayslipsPayslipIdRoute
  '/dashboard/pay-runs/$id': typeof DashboardPayRunsIdRouteWithChildren
  '/dashboard/employees/': typeof DashboardEmployeesIndexRoute
  '/dashboard/my-payslips/': typeof DashboardMyPayslipsIndexRoute
  '/dashboard/pay-runs/': typeof DashboardPayRunsIndexRoute
  '/dashboard/pay-runs/$id/': typeof DashboardPayRunsIdIndexRoute
  '/dashboard/pay-runs/$id/payslips/$payslipId': typeof DashboardPayRunsIdPayslipsPayslipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/auth/success'
    | '/auth/verify-mfa'
    | '/dashboard/contribution-tables'
    | '/dashboard/employees'
    | '/dashboard/my-payslips'
    | '/dashboard/pay-runs'
    | '/dashboard/tax-tables'
    | '/dashboard/'
    | '/dashboard/employees/$id'
    | '/dashboard/my-payslips/$payslipId'
    | '/dashboard/pay-runs/$id'
    | '/dashboard/employees/'
    | '/dashboard/my-payslips/'
    | '/dashboard/pay-runs/'
    | '/dashboard/pay-runs/$id/'
    | '/dashboard/pay-runs/$id/payslips/$payslipId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/auth/success'
    | '/auth/verify-mfa'
    | '/dashboard/contribution-tables'
    | '/dashboard/tax-tables'
    | '/dashboard'
    | '/dashboard/employees/$id'
    | '/dashboard/my-payslips/$payslipId'
    | '/dashboard/employees'
    | '/dashboard/my-payslips'
    | '/dashboard/pay-runs'
    | '/dashboard/pay-runs/$id'
    | '/dashboard/pay-runs/$id/payslips/$payslipId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/auth/success'
    | '/auth/verify-mfa'
    | '/dashboard/contribution-tables'
    | '/dashboard/employees'
    | '/dashboard/my-payslips'
    | '/dashboard/pay-runs'
    | '/dashboard/tax-tables'
    | '/dashboard/'
    | '/dashboard/employees/$id'
    | '/dashboard/my-payslips/$payslipId'
    | '/dashboard/pay-runs/$id'
    | '/dashboard/employees/'
    | '/dashboard/my-payslips/'
    | '/dashboard/pay-runs/'
    | '/dashboard/pay-runs/$id/'
    | '/dashboard/pay-runs/$id/payslips/$payslipId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  AuthVerifyMfaRoute: typeof AuthVerifyMfaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-mfa': {
      id: '/auth/verify-mfa'
      path: '/auth/verify-mfa'
      fullPath: '/auth/verify-mfa'
      preLoaderRoute: typeof AuthVerifyMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contribution-tables': {
      id: '/dashboard/contribution-tables'
      path: '/contribution-tables'
      fullPath: '/dashboard/contribution-tables'
      preLoaderRoute: typeof DashboardContributionTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees': {
      id: '/dashboard/employees'
      path: '/employees'
      fullPath: '/dashboard/employees'
      preLoaderRoute: typeof DashboardEmployeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-payslips': {
      id: '/dashboard/my-payslips'
      path: '/my-payslips'
      fullPath: '/dashboard/my-payslips'
      preLoaderRoute: typeof DashboardMyPayslipsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pay-runs': {
      id: '/dashboard/pay-runs'
      path: '/pay-runs'
      fullPath: '/dashboard/pay-runs'
      preLoaderRoute: typeof DashboardPayRunsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tax-tables': {
      id: '/dashboard/tax-tables'
      path: '/tax-tables'
      fullPath: '/dashboard/tax-tables'
      preLoaderRoute: typeof DashboardTaxTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees/': {
      id: '/dashboard/employees/'
      path: '/'
      fullPath: '/dashboard/employees/'
      preLoaderRoute: typeof DashboardEmployeesIndexRouteImport
      parentRoute: typeof DashboardEmployeesRoute
    }
    '/dashboard/employees/$id': {
      id: '/dashboard/employees/$id'
      path: '/$id'
      fullPath: '/dashboard/employees/$id'
      preLoaderRoute: typeof DashboardEmployeesIdRouteImport
      parentRoute: typeof DashboardEmployeesRoute
    }
    '/dashboard/my-payslips/': {
      id: '/dashboard/my-payslips/'
      path: '/'
      fullPath: '/dashboard/my-payslips/'
      preLoaderRoute: typeof DashboardMyPayslipsIndexRouteImport
      parentRoute: typeof DashboardMyPayslipsRoute
    }
    '/dashboard/my-payslips/$payslipId': {
      id: '/dashboard/my-payslips/$payslipId'
      path: '/$payslipId'
      fullPath: '/dashboard/my-payslips/$payslipId'
      preLoaderRoute: typeof DashboardMyPayslipsPayslipIdRouteImport
      parentRoute: typeof DashboardMyPayslipsRoute
    }
    '/dashboard/pay-runs/': {
      id: '/dashboard/pay-runs/'
      path: '/'
      fullPath: '/dashboard/pay-runs/'
      preLoaderRoute: typeof DashboardPayRunsIndexRouteImport
      parentRoute: typeof DashboardPayRunsRoute
    }
    '/dashboard/pay-runs/$id': {
      id: '/dashboard/pay-runs/$id'
      path: '/$id'
      fullPath: '/dashboard/pay-runs/$id'
      preLoaderRoute: typeof DashboardPayRunsIdRouteImport
      parentRoute: typeof DashboardPayRunsRoute
    }
    '/dashboard/pay-runs/$id/': {
      id: '/dashboard/pay-runs/$id/'
      path: '/'
      fullPath: '/dashboard/pay-runs/$id/'
      preLoaderRoute: typeof DashboardPayRunsIdIndexRouteImport
      parentRoute: typeof DashboardPayRunsIdRoute
    }
    '/dashboard/pay-runs/$id/payslips/$payslipId': {
      id: '/dashboard/pay-runs/$id/payslips/$payslipId'
      path: '/payslips/$payslipId'
      fullPath: '/dashboard/pay-runs/$id/payslips/$payslipId'
      preLoaderRoute: typeof DashboardPayRunsIdPayslipsPayslipIdRouteImport
      parentRoute: typeof DashboardPayRunsIdRoute
    }
  }
}

interface DashboardEmployeesRouteChildren {
  DashboardEmployeesIdRoute: typeof DashboardEmployeesIdRoute
  DashboardEmployeesIndexRoute: typeof DashboardEmployeesIndexRoute
}

const DashboardEmployeesRouteChildren: DashboardEmployeesRouteChildren = {
  DashboardEmployeesIdRoute: DashboardEmployeesIdRoute,
  DashboardEmployeesIndexRoute: DashboardEmployeesIndexRoute,
}

const DashboardEmployeesRouteWithChildren =
  DashboardEmployeesRoute._addFileChildren(DashboardEmployeesRouteChildren)

interface DashboardMyPayslipsRouteChildren {
  DashboardMyPayslipsPayslipIdRoute: typeof DashboardMyPayslipsPayslipIdRoute
  DashboardMyPayslipsIndexRoute: typeof DashboardMyPayslipsIndexRoute
}

const DashboardMyPayslipsRouteChildren: DashboardMyPayslipsRouteChildren = {
  DashboardMyPayslipsPayslipIdRoute: DashboardMyPayslipsPayslipIdRoute,
  DashboardMyPayslipsIndexRoute: DashboardMyPayslipsIndexRoute,
}

const DashboardMyPayslipsRouteWithChildren =
  DashboardMyPayslipsRoute._addFileChildren(DashboardMyPayslipsRouteChildren)

interface DashboardPayRunsIdRouteChildren {
  DashboardPayRunsIdIndexRoute: typeof DashboardPayRunsIdIndexRoute
  DashboardPayRunsIdPayslipsPayslipIdRoute: typeof DashboardPayRunsIdPayslipsPayslipIdRoute
}

const DashboardPayRunsIdRouteChildren: DashboardPayRunsIdRouteChildren = {
  DashboardPayRunsIdIndexRoute: DashboardPayRunsIdIndexRoute,
  DashboardPayRunsIdPayslipsPayslipIdRoute:
    DashboardPayRunsIdPayslipsPayslipIdRoute,
}

const DashboardPayRunsIdRouteWithChildren =
  DashboardPayRunsIdRoute._addFileChildren(DashboardPayRunsIdRouteChildren)

interface DashboardPayRunsRouteChildren {
  DashboardPayRunsIdRoute: typeof DashboardPayRunsIdRouteWithChildren
  DashboardPayRunsIndexRoute: typeof DashboardPayRunsIndexRoute
}

const DashboardPayRunsRouteChildren: DashboardPayRunsRouteChildren = {
  DashboardPayRunsIdRoute: DashboardPayRunsIdRouteWithChildren,
  DashboardPayRunsIndexRoute: DashboardPayRunsIndexRoute,
}

const DashboardPayRunsRouteWithChildren =
  DashboardPayRunsRoute._addFileChildren(DashboardPayRunsRouteChildren)

interface DashboardRouteChildren {
  DashboardContributionTablesRoute: typeof DashboardContributionTablesRoute
  DashboardEmployeesRoute: typeof DashboardEmployeesRouteWithChildren
  DashboardMyPayslipsRoute: typeof DashboardMyPayslipsRouteWithChildren
  DashboardPayRunsRoute: typeof DashboardPayRunsRouteWithChildren
  DashboardTaxTablesRoute: typeof DashboardTaxTablesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardContributionTablesRoute: DashboardContributionTablesRoute,
  DashboardEmployeesRoute: DashboardEmployeesRouteWithChildren,
  DashboardMyPayslipsRoute: DashboardMyPayslipsRouteWithChildren,
  DashboardPayRunsRoute: DashboardPayRunsRouteWithChildren,
  DashboardTaxTablesRoute: DashboardTaxTablesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  AuthVerifyMfaRoute: AuthVerifyMfaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
